POST http://localhost:8081/api/v1/quote HTTP/1.1
Content-Type: application/json

{
   "recipient":{
      "address":{
         "zipcode":"29161376"
      }
   },
   "volumes":[
      {
         "category":7,
         "amount":1,
         "unitary_weight":5,
         "price":349,
         "sku":"abc-teste-123",
         "height":0.2,
         "width":0.2,
         "length":0.2
      },
      {
         "category":7,
         "amount":2,
         "unitary_weight":4,
         "price":556,
         "sku":"abc-teste-527",
         "height":0.4,
         "width":0.6,
         "length":0.15
      }
   ]
}

#####

GET http://localhost:8081/api/v1/metrics?last_quotes=15
Content-Type: application/json

#####
GET http://localhost:8081/api/v1/metrics
Content-Type: application/json